from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from core import views
from core.views import CustomLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('operator/', views.operator_dashboard, name='operator_dashboard'),
    path('telegram/<int:telegram_id>/', views.view_telegram, name='view_telegram'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('journal/', views.telegram_journal, name='telegram_journal'),
    path('export-excel/', views.export_telegrams_excel, name='export_excel'),
    path('edit/<int:pk>/', views.edit_telegram, name='edit_telegram'),
    path('copy/<int:pk>/', views.copy_telegram, name='copy_telegram'),
    path('delete/<int:pk>/', views.delete_telegram, name='delete_telegram'),
    path('print/<int:pk>/', views.print_telegram, name='print_telegram'),
    path('mark-as-read/<int:recipient_id>/', views.mark_as_read, name='mark_as_read'),
    path('mark-as-read-and-view/<int:recipient_id>/', views.mark_as_read_and_view, name='mark_as_read_and_view'),
    path('telegram/<int:telegram_id>/sign/', views.sign_telegram, name='sign_telegram'),
    path('departments/', views.department_list, name='department_list'),
    path('departments/create/', views.department_create, name='department_create'),
    path('departments/<int:pk>/edit/', views.department_edit, name='department_edit'),
    path('departments/<int:pk>/delete/', views.department_delete, name='department_delete'),
    path('departments/<int:department_id>/users/', views.department_users, name='department_users'),
    path('positions/', views.position_list, name='position_list'),
    path('positions/create/', views.position_create, name='position_create'),
    path('positions/<int:pk>/edit/', views.position_edit, name='position_edit'),
    path('positions/<int:pk>/delete/', views.position_delete, name='position_delete'),
    path('operatorzones/', views.operatorzone_list, name='operatorzone_list'),
    path('operatorzones/create/', views.operatorzone_create, name='operatorzone_create'),
    path('operatorzones/<int:pk>/edit/', views.operatorzone_edit, name='operatorzone_edit'),
    path('operatorzones/<int:pk>/delete/', views.operatorzone_delete, name='operatorzone_delete'),
    path('telegram/create/', views.create_telegram_page, name='create_telegram_page'),
    path('get-positions/<int:department_id>/', views.get_positions, name='get_positions'),
    path('get-users/<int:position_id>/', views.get_users, name='get_users'),
    path('reports/', views.reports, name='reports'),
    path('export-report-excel/', views.export_report_excel, name='export_report_excel'),
    path('get-approvers/<int:department_id>/', views.get_approvers_by_department, name='get_approvers_by_department'),
    path('get-recipients/', views.get_recipients_by_departments, name='get_recipients'),
    path('get-approvers/', views.get_approvers_by_departments, name='get_approvers'),
    path('mass-delete/', views.mass_delete, name='mass_delete'),
    path('mass-copy/', views.mass_copy, name='mass_copy'),
    path('upload-word/', views.upload_word, name='upload_word'),
    path('telegram-detail/<int:telegram_id>/', views.telegram_detail_json, name='telegram_detail_json'),
    path('profile/', views.profile, name='profile'),
    path('api/departments-with-users/', views.departments_with_users, name='departments_with_users'),
    path('api/approvers-tree/', views.approvers_tree, name='approvers_tree'),
    path('send-telegram/', views.send_telegram, name='send_telegram'),
    path('reset-to-draft/', views.reset_to_draft, name='reset_to_draft'),
]