# Generated by Django 6.0.3 on 2026-04-02 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст телеграммы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SENT', 'Отправлена'), ('DELIVERED', 'Доставлена'), ('READ', 'Прочитана')], default='DRAFT', max_length=10, verbose_name='Статус')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegrams', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_telegrams', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
        ),
    ]
