# Generated by Django 6.0.3 on 2026-04-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('PHONE', 'По телефону'), ('FAX', 'По факсу'), ('COURIER', 'Экспедиция')], max_length=10, null=True, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения'),
        ),
    ]
