# Generated by Django 6.0.3 on 2026-04-02 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_telegram_delivery_method_telegram_read_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Вход в систему'), ('LOGOUT', 'Выход из системы'), ('CREATE_TELEGRAM', 'Создание телеграммы'), ('VIEW_TELEGRAM', 'Просмотр телеграммы'), ('DELIVER_TELEGRAM', 'Доставка телеграммы оператором')], max_length=20, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал действия',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-timestamp'],
            },
        ),
    ]
