# Generated by Django 6.0.3 on 2026-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телеграммы'),
        ),
    ]
