# Generated by Django 6.0.3 on 2026-04-04 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_department_user_department_operatorzone_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegrams_to_approve', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='Подписана'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='Требуется согласование'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подписи'),
        ),
        migrations.CreateModel(
            name='TelegramApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок согласования')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('APPROVED', 'Согласовано'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
                ('telegram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.telegram')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TelegramRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('READ', 'Прочитано'), ('SIGNED', 'Подписано'), ('APPROVED', 'Согласовано')], default='PENDING', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('telegram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.telegram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'unique_together': {('telegram', 'user')},
            },
        ),
    ]
