# Generated by Django 6.0.3 on 2026-04-21 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_telegram_approver_telegram_is_signed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('text', models.TextField(verbose_name='Текст шаблона')),
                ('is_default', models.BooleanField(default=False, verbose_name='Использовать по умолчанию')),
            ],
            options={
                'verbose_name': 'Шаблон телеграммы',
                'verbose_name_plural': 'Шаблоны телеграмм',
            },
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='telegramrecipient',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='telegramrecipient',
            name='signed_at',
        ),
        migrations.AddField(
            model_name='telegram',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='telegrams_to_approve', to=settings.AUTH_USER_MODEL, verbose_name='Подписанты'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Обычная'), ('URGENT', 'Срочная')], default='NORMAL', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='telegramrecipient',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('PHONE', 'По телефону'), ('FAX', 'По факсу'), ('COURIER', 'Экспедиция')], max_length=10, null=True, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_telegrams', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='Требуется подпись'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('SENT', 'Отправлена'), ('DELIVERED', 'Доставлена'), ('READ', 'Прочитана'), ('SIGNED', 'Подписана')], default='DRAFT', max_length=10, verbose_name='Общий статус'),
        ),
        migrations.AlterField(
            model_name='telegramrecipient',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает'), ('READ', 'Прочитано')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='TelegramSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('telegram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='core.telegram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подписант')),
            ],
            options={
                'unique_together': {('telegram', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='TelegramApproval',
        ),
    ]
