# Generated by Django 6.0.3 on 2026-04-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_telegramtemplate_remove_department_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramrecipient',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='status',
            field=models.CharField(choices=[('SENT', 'Отправлена'), ('READ', 'Прочитана'), ('SIGNED', 'Подписана')], default='SENT', max_length=10, verbose_name='Общий статус'),
        ),
        migrations.AlterField(
            model_name='telegramtemplate',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='По умолчанию'),
        ),
    ]
