# Generated by Django 6.0.3 on 2026-04-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_telegramrecipient_delivered_at_alter_telegram_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Вход в систему'), ('LOGOUT', 'Выход из системы'), ('CREATE_TELEGRAM', 'Создание телеграммы'), ('VIEW_TELEGRAM', 'Просмотр телеграммы'), ('DELIVER_TELEGRAM', 'Доставка телеграммы оператором'), ('NOTIFY', 'Уведомление оператором')], max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='telegramrecipient',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает'), ('READ', 'Прочитано'), ('DELIVERED', 'Доставлено оператором')], default='PENDING', max_length=10),
        ),
    ]
