# Generated by Django 6.0.3 on 2026-04-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_log_action_alter_telegramrecipient_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramrecipient',
            options={'verbose_name': 'Получатель телеграммы', 'verbose_name_plural': 'Получатели телеграмм'},
        ),
        migrations.AddField(
            model_name='telegramrecipient',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='Уведомлён оператором'),
        ),
        migrations.AddField(
            model_name='telegramrecipient',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего уведомления'),
        ),
    ]
