# Generated by Django 6.0.3 on 2026-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_telegramrecipient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='signature',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Электронная подпись'),
        ),
    ]
